-- If any Oracle Forms PL/SQL routine (triggers, procedures, functions) has only Oracle Forms internal built-ins and/or these custom routines, this routine can be discarded.
DECLARE
   p_prc_name varchar2(1000) := 'M_LOAD_FORM_CUSTOM_DISPOSA: ';

BEGIN
   DBMS_OUTPUT.put_line (p_prc_name);

-- DEFAULT FOR ALL CONVERSIONS
   insert into m_load_form_custom_disposa (txt_custom_disposable_text, id_disposable_text_type, txt_disposable_has_params, txt_disposable_is_package) values ('CHECK_PACKAGE_FAILURE',     PKG_M_LOAD_FORM_DISPOS_TXT_TYP.fu_ret_disposable_text_type_i ('CUSTOM'), 'N', 'N');
   insert into m_load_form_custom_disposa (txt_custom_disposable_text, id_disposable_text_type, txt_disposable_has_params, txt_disposable_is_package) values ('CLEAR_ALL_MASTER_DETAILS',  PKG_M_LOAD_FORM_DISPOS_TXT_TYP.fu_ret_disposable_text_type_i ('CUSTOM'), 'N', 'N');
   insert into m_load_form_custom_disposa (txt_custom_disposable_text, id_disposable_text_type, txt_disposable_has_params, txt_disposable_is_package) values ('QUERY_MASTER_DETAILS',      PKG_M_LOAD_FORM_DISPOS_TXT_TYP.fu_ret_disposable_text_type_i ('CUSTOM'), 'N', 'N');

   commit;

   DBMS_OUTPUT.put_line ('COMMIT.');

EXCEPTION
   when others then
      rollback;
      DBMS_OUTPUT.put_line ('Erro ' || p_prc_name || to_char (sqlcode) || ' - ' || sqlerrm);
END;
/

-- These Forms triggers will be discarded according to their rules (on form level, on block level, on item level).
DECLARE
   p_prc_name varchar2(1000) := 'M_DISPOSABLE_FORM_TRG_LVL: ';

BEGIN
   DBMS_OUTPUT.put_line (p_prc_name);

   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('DELETE-PROCEDURE'),         'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('INSERT-PROCEDURE'),         'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-CLRBLK'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-CLRFRM'),               'Y', 'Y', 'Y');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-CLRREC'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-COMMIT'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-CQUERY'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-CREREC'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-DELREC'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-DOWN'),                 'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-DUP-ITEM'),             'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-DUPREC'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-EDIT'),                 'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-ENTQRY'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-EXEQRY'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-EXIT'),                 'Y', 'Y', 'Y');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-F0'),                   'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-F1'),                   'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-F2'),                   'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-F3'),                   'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-F4'),                   'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-F5'),                   'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-F6'),                   'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-F7'),                   'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-F8'),                   'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-F9'),                   'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-HELP'),                 'Y', 'Y', 'Y');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-LISTVAL'),              'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-MENU'),                 'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-NXT-ITEM'),             'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-NXTBLK'),               'Y', 'Y', 'Y');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-NXTKEY'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-NXTREC'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-NXTSET'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-OTHERS'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-PRINT'),                'Y', 'Y', 'Y');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-PRV-ITEM'),             'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-PRVBLK'),               'Y', 'Y', 'Y');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-PRVREC'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-SCRDOWN'),              'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-SCRUP'),                'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-UP'),                   'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('KEY-UPDREC'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('LOCK-PROCEDURE'),           'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-CHECK-DELETE-MASTER'),   'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-CHECK-UNIQUE'),          'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-CLEAR-DETAILS'),         'Y', 'Y', 'Y');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-CLOSE'),                 'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-COLUMN-SECURITY'),       'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-COMMIT'),                'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-COUNT'),                 'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-DELETE'),                'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-DISPATCH-EVENT'),        'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-ERROR'),                 'Y', 'Y', 'Y');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-FETCH'),                 'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-INSERT'),                'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-LOCK'),                  'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-LOGON'),                 'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-LOGOUT'),                'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-MESSAGE'),               'Y', 'Y', 'Y');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-POPULATE-DETAILS'),      'Y', 'Y', 'Y');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-ROLLBACK'),              'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-SAVEPOINT'),             'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-SELECT'),                'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-SEQUENCE-NUMBER'),       'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('ON-UPDATE'),                'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('POST-BLOCK'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('POST-CHANGE'),              'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('POST-DATABASE-COMMIT'),     'Y', 'Y', 'Y');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('POST-DELETE'),              'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('POST-FORM'),                'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('POST-FORMS-COMMIT'),        'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('POST-INSERT'),              'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('POST-LOGON'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('POST-LOGOUT'),              'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('POST-QUERY'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('POST-RECORD'),              'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('POST-SELECT'),              'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('POST-TEXT-ITEM'),           'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('POST-UPDATE'),              'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('PRE-BLOCK'),                'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('PRE-COMMIT'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('PRE-DELETE'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('PRE-FORM'),                 'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('PRE-INSERT'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('PRE-LOGON'),                'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('PRE-LOGOUT'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('PRE-POPUP-MENU'),           'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('PRE-QUERY'),                'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('PRE-RECORD'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('PRE-SELECT'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('PRE-TEXT-ITEM'),            'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('PRE-UPDATE'),               'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('QUERY-PROCEDURE'),          'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('UPDATE-PROCEDURE'),         'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-BUTTON-PRESSED'),      'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-CHECKBOX-CHANGED'),    'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-CLEAR-BLOCK'),         'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-CREATE-RECORD'),       'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-CUSTOM-ITEM-EVENT'),   'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-DATABASE-RECORD'),     'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-FORM-NAVIGATE'),       'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-IMAGE-ACTIVATED'),     'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-IMAGE-PRESSED'),       'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-LIST-ACTIVATED'),      'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-LIST-CHANGED'),        'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-MOUSE-CLICK'),         'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-MOUSE-DOUBLECLICK'),   'Y', 'Y', 'Y');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-MOUSE-DOWN'),          'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-MOUSE-ENTER'),         'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-MOUSE-LEAVE'),         'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-MOUSE-MOVE'),          'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-MOUSE-UP'),            'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-NEW-BLOCK-INSTANCE'),  'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-NEW-FORM-INSTANCE'),   'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-NEW-ITEM-INSTANCE'),   'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-NEW-RECORD-INSTANCE'), 'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-RADIO-CHANGED'),       'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-REMOVE-RECORD'),       'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-TAB-PAGE-CHANGED'),    'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-TIMER-EXPIRED'),       'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-TREE-NODE-ACTIVATED'), 'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-TREE-NODE-EXPANDED'),  'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-TREE-NODE-SELECTED'),  'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-VALIDATE-ITEM'),       'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-VALIDATE-RECORD'),     'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-WINDOW-ACTIVATED'),    'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-WINDOW-CLOSED'),       'Y', 'Y', 'Y');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-WINDOW-DEACTIVATED'),  'N', 'N', 'N');
   insert into m_disposable_form_trg_lvl (id_disposable_form_trg, txt_dispos_trg_form_level, txt_dispos_trg_block_level, txt_dispos_trg_item_level) values (PKG_M_DISPOSABLE_CONTENTS.fu_ret_id_txt_disposable_txt_i ('WHEN-WINDOW-RESIZED'),      'N', 'N', 'N');

   commit;

   DBMS_OUTPUT.put_line ('COMMIT.');

EXCEPTION
   when others then
      rollback;
      DBMS_OUTPUT.put_line ('Erro ' || p_prc_name || to_char (sqlcode) || ' - ' || sqlerrm);
END;
/
