drop trigger t01_m_disposable_contents;
drop trigger t01_m_disposable_form_trg_lvl;
drop trigger t01_m_form_keywords;
drop trigger t01_m_form_keywords_values;
drop trigger t01_m_languages;
drop trigger t01_m_load_form;
drop trigger t01_m_load_form_block_relation;
drop trigger t01_m_load_form_blocks_items;
drop trigger t01_m_load_form_custom_disposa;
drop trigger t01_m_load_form_dispos_txt_typ;
drop trigger t01_m_load_form_glob_syst_parm;
drop trigger t01_m_load_form_lines;
drop trigger t01_m_load_form_list_values;
drop trigger t01_m_load_form_plsql_contents;
drop trigger t01_m_load_form_plsql_disc_rsn;
drop trigger t01_m_load_form_plsql_params;
drop trigger t01_m_load_form_record_groups;
drop trigger t01_m_load_form_static_values;
drop trigger t01_m_load_form_trigger_types;
drop trigger t02_m_load_form_plsql_contents;

drop package body pkg_import_form;
drop package body pkg_m_disposable_contents;
drop package body pkg_m_disposable_form_trg_lvl;
drop package body pkg_m_form_keywords;
drop package body pkg_m_form_keywords_values;
drop package body pkg_m_languages;
drop package body pkg_m_load_form_block_relation;
drop package body pkg_m_load_form_blocks_items;
drop package body pkg_m_load_form_custom_disposa;
drop package body pkg_m_load_form_dispos_txt_typ;
drop package body pkg_m_load_form_glob_syst_parm;
drop package body pkg_m_load_form_lines;
drop package body pkg_m_load_form_list_values;
drop package body pkg_m_load_form_plsql_contents;
drop package body pkg_m_load_form_plsql_disc_rsn;
drop package body pkg_m_load_form_plsql_params;
drop package body pkg_m_load_form_record_groups;
drop package body pkg_m_load_form_static_values;
drop package body pkg_m_load_form_trigger_types;
drop package body pkg_m_validacao;

drop package pkg_import_form;
drop package pkg_m_disposable_contents;
drop package pkg_m_disposable_form_trg_lvl;
drop package pkg_m_form_keywords;
drop package pkg_m_form_keywords_values;
drop package pkg_m_languages;
drop package pkg_m_load_form_block_relation;
drop package pkg_m_load_form_blocks_items;
drop package pkg_m_load_form_custom_disposa;
drop package pkg_m_load_form_dispos_txt_typ;
drop package pkg_m_load_form_glob_syst_parm;
drop package pkg_m_load_form_lines;
drop package pkg_m_load_form_list_values;
drop package pkg_m_load_form_plsql_contents;
drop package pkg_m_load_form_plsql_disc_rsn;
drop package pkg_m_load_form_plsql_params;
drop package pkg_m_load_form_record_groups;
drop package pkg_m_load_form_static_values;
drop package pkg_m_load_form_trigger_types;
drop package pkg_m_validacao;

drop table m_disposable_contents      cascade constraints;
drop table m_disposable_form_trg_lvl  cascade constraints;
drop table m_form_keywords            cascade constraints;
drop table m_form_keywords_values     cascade constraints;
drop table m_languages                cascade constraints;
drop table m_load_form                cascade constraints;
drop table m_load_form_block_relation cascade constraints;
drop table m_load_form_blocks_items   cascade constraints;
drop table m_load_form_custom_disposa cascade constraints;
drop table m_load_form_dispos_txt_typ cascade constraints;
drop table m_load_form_glob_syst_parm cascade constraints;
drop table m_load_form_lines          cascade constraints;
drop table m_load_form_list_values    cascade constraints;
drop table m_load_form_plsql_contents cascade constraints;
drop table m_load_form_plsql_disc_rsn cascade constraints;
drop table m_load_form_plsql_params   cascade constraints;
drop table m_load_form_record_groups  cascade constraints;
drop table m_load_form_static_values  cascade constraints;
drop table m_load_form_trigger_types  cascade constraints;

drop sequence s_m_disposable_contents;
drop sequence s_m_disposable_form_trg_lvl;
drop sequence s_m_form_keywords;
drop sequence s_m_form_keywords_values;
drop sequence s_m_languages;
drop sequence s_m_load_form;
drop sequence s_m_load_form_block_relation;
drop sequence s_m_load_form_blocks_items;
drop sequence s_m_load_form_custom_disposa;
drop sequence s_m_load_form_dispos_txt_typ;
drop sequence s_m_load_form_glob_syst_parm;
drop sequence s_m_load_form_lines;
drop sequence s_m_load_form_list_values;
drop sequence s_m_load_form_plsql_contents;
drop sequence s_m_load_form_plsql_disc_rsn;
drop sequence s_m_load_form_plsql_params;
drop sequence s_m_load_form_record_groups;
drop sequence s_m_load_form_static_values;
drop sequence s_m_load_form_trigger_types;
