-- ACCORDING TO DATABASE DATA BLOCKS

-- DATABASE DATA BLOCK: T_SCHOOL_MEMBERS
CREATE TABLE T_SCHOOL_MEMBERS (
  SCH_ME_ID                       NUMBER(38,0)
, SCH_ME_NAME                     VARCHAR2(100)
, SCH_ME_SC_ID                    NUMBER(38,0)
, SCH_ME_MT_ID                    NUMBER(38,0)
);
/


-- ACCORDING TO QUERY DATA SOURCE

-- QUERY DATA SOURCE COLUMNS: BLOCK: T_SCHOOL_MEMBERS
CREATE TABLE T_SCHOOL_MEMBERS (
  SCH_ME_ID                       NUMBER(38,0) NOT NULL
, SCH_ME_NAME                     VARCHAR2(100)
, SCH_ME_SC_ID                    NUMBER(38,0) NOT NULL
, SCH_ME_MT_ID                    NUMBER(38,0) NOT NULL
);
/

