set serveroutput on size unlimited
set define off

DECLARE
   p_prc_name varchar2(50) := 'INSERT INTO DOMAIN TABLES: ';

BEGIN
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_COUNTRY', 'RB_USA',    'USA',    '1', '', '', '', '', '',                     ''    );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_COUNTRY', 'RB_CANADA', 'Canada', '2', '', '', '', '', '',                     ''    );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_COUNTRY', 'RB_OTHER',  'Other',  '0', '', '', '', '', '',                     ''    );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'OTHER, NOT LISTED',    'OO'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Alaska',               'AK'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Alabama',              'AL'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Arkansas',             'AR'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Arizona',              'AZ'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'California',           'CA'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Colorado',             'CO'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Connecticut',          'CT'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'District of Columbia', 'DC'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Delaware',             'DE'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Florida',              'FL'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Georgia',              'GA'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Hawaii',               'HI'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Iowa',                 'IA'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Idaho',                'ID'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Illinois',             'IL'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Indiana',              'IN'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Kansas',               'KS'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Kentucky',             'KY'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Louisiana',            'LA'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Massachusetts',        'MA'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Maryland',             'MD'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Maine',                'ME'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Michigan',             'MI'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Minnesota',            'MN'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Missouri',             'MO'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Mississippi',          'MS'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Montana',              'MT'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'North Carolina',       'NC'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'North Dakota',         'ND'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Nebraska',             'NE'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'New Hampshire',        'NH'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'New Jersey',           'NJ'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'New Mexico',           'NM'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Nevada',               'NV'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'New York',             'NY'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Ohio',                 'OH'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Oklahoma',             'OK'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Oregon',               'OR'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Pennsylvania',         'PA'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Rhode Island',         'RI'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'South Carolina',       'SC'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'South Dakota',         'SD'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Tennessee',            'TN'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Texas',                'TX'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Utah',                 'UT'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Virginia',             'VA'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Vermont',              'VT'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Washington',           'WA'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Wisconsin',            'WI'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'West Virginia',        'WV'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', 'Wyoming',              'WY'  );
   insert into domain_table (field_01, field_02, field_03, field_04, field_05, field_06, field_07, field_08, field_09, field_10, field_11, field_12) values ('BLOCK ITEM STATIC CONTENTS', 'T_SCHOOL', 'SCH_STATE',   '',          '',       '',  '', '', '', '', '',                     ''    );

   commit;

EXCEPTION
   when others then
      rollback;
      DBMS_OUTPUT.put_line ('Error ' || p_prc_name || to_char (sqlcode) || ' - ' || sqlerrm);
END;
/
